# base image source: https://github.com/hseeberger/scala-sbt
FROM hseeberger/scala-sbt

# clone connect four game repository
RUN git clone https://github.com/Schmork/game-connect-four.git /soar
  
# Define working directory
WORKDIR /root
